# Generated by Django 5.2.8 on 2026-04-12 14:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_phoneotp_remove_company_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Main Malayalam/English description')),
                ('gender', models.CharField(choices=[('Any', 'Male / Female'), ('Male', 'Male Only'), ('Female', 'Female Only')], default='Any', max_length=10)),
                ('salary', models.CharField(max_length=100)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('timing', models.CharField(blank=True, max_length=100, null=True)),
                ('benefits', models.TextField(blank=True, help_text='e.g., ESI & PF, Food & Accommodation', null=True)),
                ('requirements', models.TextField(blank=True, help_text='e.g., Two wheeler must, Arabic knowledge must', null=True)),
                ('is_urgent', models.BooleanField(default=False, help_text='Check this to show 📢 URGENT VACANCY tag')),
                ('contact_info', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.category')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
