# Generated by Django 5.2.8 on 2026-04-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Reviewed', 'Reviewed'), ('Interview', 'Interviewing'), ('Onboarding', 'Hired / Onboarding'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
