# Generated by Django 5.2.8 on 2026-04-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Private notes hidden from the candidate.'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='rating',
            field=models.IntegerField(default=0, help_text='1 to 5 star rating.'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume_link',
            field=models.URLField(blank=True),
        ),
    ]
